// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SkuMutationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkuMutationResponse{}

// SkuMutationResponse Core-backed SKU returned after a create or update operation.
type SkuMutationResponse struct {
	// Unique SKU identifier
	Id string `json:"id"`
	// ID of the Site that owns the SKU
	SiteId string `json:"siteId"`
	// Human-readable SKU description
	Description string `json:"description"`
	// Core SKU schema version
	SchemaVersion int32 `json:"schemaVersion"`
	// Optional device type identifier
	DeviceType NullableString `json:"deviceType,omitempty"`
	// Machine IDs currently associated with the SKU
	AssociatedMachineIds []string              `json:"associatedMachineIds"`
	Components           SkuMutationComponents `json:"components"`
	// Core creation timestamp when available
	Created NullableTime `json:"created,omitempty"`
}

type _SkuMutationResponse SkuMutationResponse

// NewSkuMutationResponse instantiates a new SkuMutationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkuMutationResponse(id string, siteId string, description string, schemaVersion int32, associatedMachineIds []string, components SkuMutationComponents) *SkuMutationResponse {
	this := SkuMutationResponse{}
	this.Id = id
	this.SiteId = siteId
	this.Description = description
	this.SchemaVersion = schemaVersion
	this.AssociatedMachineIds = associatedMachineIds
	this.Components = components
	return &this
}

// NewSkuMutationResponseWithDefaults instantiates a new SkuMutationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkuMutationResponseWithDefaults() *SkuMutationResponse {
	this := SkuMutationResponse{}
	return &this
}

// GetId returns the Id field value
func (o *SkuMutationResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SkuMutationResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SkuMutationResponse) SetId(v string) {
	o.Id = v
}

// GetSiteId returns the SiteId field value
func (o *SkuMutationResponse) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *SkuMutationResponse) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *SkuMutationResponse) SetSiteId(v string) {
	o.SiteId = v
}

// GetDescription returns the Description field value
func (o *SkuMutationResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SkuMutationResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SkuMutationResponse) SetDescription(v string) {
	o.Description = v
}

// GetSchemaVersion returns the SchemaVersion field value
func (o *SkuMutationResponse) GetSchemaVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value
// and a boolean to check if the value has been set.
func (o *SkuMutationResponse) GetSchemaVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SchemaVersion, true
}

// SetSchemaVersion sets field value
func (o *SkuMutationResponse) SetSchemaVersion(v int32) {
	o.SchemaVersion = v
}

// GetDeviceType returns the DeviceType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SkuMutationResponse) GetDeviceType() string {
	if o == nil || IsNil(o.DeviceType.Get()) {
		var ret string
		return ret
	}
	return *o.DeviceType.Get()
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SkuMutationResponse) GetDeviceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceType.Get(), o.DeviceType.IsSet()
}

// HasDeviceType returns a boolean if a field has been set.
func (o *SkuMutationResponse) HasDeviceType() bool {
	if o != nil && o.DeviceType.IsSet() {
		return true
	}

	return false
}

// SetDeviceType gets a reference to the given NullableString and assigns it to the DeviceType field.
func (o *SkuMutationResponse) SetDeviceType(v string) {
	o.DeviceType.Set(&v)
}

// SetDeviceTypeNil sets the value for DeviceType to be an explicit nil
func (o *SkuMutationResponse) SetDeviceTypeNil() {
	o.DeviceType.Set(nil)
}

// UnsetDeviceType ensures that no value is present for DeviceType, not even an explicit nil
func (o *SkuMutationResponse) UnsetDeviceType() {
	o.DeviceType.Unset()
}

// GetAssociatedMachineIds returns the AssociatedMachineIds field value
func (o *SkuMutationResponse) GetAssociatedMachineIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AssociatedMachineIds
}

// GetAssociatedMachineIdsOk returns a tuple with the AssociatedMachineIds field value
// and a boolean to check if the value has been set.
func (o *SkuMutationResponse) GetAssociatedMachineIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssociatedMachineIds, true
}

// SetAssociatedMachineIds sets field value
func (o *SkuMutationResponse) SetAssociatedMachineIds(v []string) {
	o.AssociatedMachineIds = v
}

// GetComponents returns the Components field value
func (o *SkuMutationResponse) GetComponents() SkuMutationComponents {
	if o == nil {
		var ret SkuMutationComponents
		return ret
	}

	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value
// and a boolean to check if the value has been set.
func (o *SkuMutationResponse) GetComponentsOk() (*SkuMutationComponents, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Components, true
}

// SetComponents sets field value
func (o *SkuMutationResponse) SetComponents(v SkuMutationComponents) {
	o.Components = v
}

// GetCreated returns the Created field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SkuMutationResponse) GetCreated() time.Time {
	if o == nil || IsNil(o.Created.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Created.Get()
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SkuMutationResponse) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Created.Get(), o.Created.IsSet()
}

// HasCreated returns a boolean if a field has been set.
func (o *SkuMutationResponse) HasCreated() bool {
	if o != nil && o.Created.IsSet() {
		return true
	}

	return false
}

// SetCreated gets a reference to the given NullableTime and assigns it to the Created field.
func (o *SkuMutationResponse) SetCreated(v time.Time) {
	o.Created.Set(&v)
}

// SetCreatedNil sets the value for Created to be an explicit nil
func (o *SkuMutationResponse) SetCreatedNil() {
	o.Created.Set(nil)
}

// UnsetCreated ensures that no value is present for Created, not even an explicit nil
func (o *SkuMutationResponse) UnsetCreated() {
	o.Created.Unset()
}

func (o SkuMutationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkuMutationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["siteId"] = o.SiteId
	toSerialize["description"] = o.Description
	toSerialize["schemaVersion"] = o.SchemaVersion
	if o.DeviceType.IsSet() {
		toSerialize["deviceType"] = o.DeviceType.Get()
	}
	toSerialize["associatedMachineIds"] = o.AssociatedMachineIds
	toSerialize["components"] = o.Components
	if o.Created.IsSet() {
		toSerialize["created"] = o.Created.Get()
	}
	return toSerialize, nil
}

func (o *SkuMutationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"siteId",
		"description",
		"schemaVersion",
		"associatedMachineIds",
		"components",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkuMutationResponse := _SkuMutationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkuMutationResponse)

	if err != nil {
		return err
	}

	*o = SkuMutationResponse(varSkuMutationResponse)

	return err
}

type NullableSkuMutationResponse struct {
	value *SkuMutationResponse
	isSet bool
}

func (v NullableSkuMutationResponse) Get() *SkuMutationResponse {
	return v.value
}

func (v *NullableSkuMutationResponse) Set(val *SkuMutationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSkuMutationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSkuMutationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkuMutationResponse(val *SkuMutationResponse) *NullableSkuMutationResponse {
	return &NullableSkuMutationResponse{value: val, isSet: true}
}

func (v NullableSkuMutationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkuMutationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
