// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SkuDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkuDeleteRequest{}

// SkuDeleteRequest Request data to delete a SKU from a Site's NICo Core service.
type SkuDeleteRequest struct {
	// ID of the Site that owns the SKU
	SiteId string `json:"siteId"`
}

type _SkuDeleteRequest SkuDeleteRequest

// NewSkuDeleteRequest instantiates a new SkuDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkuDeleteRequest(siteId string) *SkuDeleteRequest {
	this := SkuDeleteRequest{}
	this.SiteId = siteId
	return &this
}

// NewSkuDeleteRequestWithDefaults instantiates a new SkuDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkuDeleteRequestWithDefaults() *SkuDeleteRequest {
	this := SkuDeleteRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *SkuDeleteRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *SkuDeleteRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *SkuDeleteRequest) SetSiteId(v string) {
	o.SiteId = v
}

func (o SkuDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkuDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	return toSerialize, nil
}

func (o *SkuDeleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkuDeleteRequest := _SkuDeleteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkuDeleteRequest)

	if err != nil {
		return err
	}

	*o = SkuDeleteRequest(varSkuDeleteRequest)

	return err
}

type NullableSkuDeleteRequest struct {
	value *SkuDeleteRequest
	isSet bool
}

func (v NullableSkuDeleteRequest) Get() *SkuDeleteRequest {
	return v.value
}

func (v *NullableSkuDeleteRequest) Set(val *SkuDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSkuDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSkuDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkuDeleteRequest(val *SkuDeleteRequest) *NullableSkuDeleteRequest {
	return &NullableSkuDeleteRequest{value: val, isSet: true}
}

func (v NullableSkuDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkuDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
