/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SkuUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkuUpdateRequest{}

// SkuUpdateRequest Request data to update a SKU on a Site's NICo Core service. At least one of description, schemaVersion, deviceType, or components must be provided.
type SkuUpdateRequest struct {
	// ID of the Site that owns the SKU
	SiteId string `json:"siteId"`
	// Replacement SKU description
	Description *string `json:"description,omitempty"`
	// Replacement Core SKU schema version
	SchemaVersion *int32 `json:"schemaVersion,omitempty"`
	// Replacement device type identifier
	DeviceType *string        `json:"deviceType,omitempty"`
	Components *SkuComponents `json:"components,omitempty"`
}

type _SkuUpdateRequest SkuUpdateRequest

// NewSkuUpdateRequest instantiates a new SkuUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkuUpdateRequest(siteId string) *SkuUpdateRequest {
	this := SkuUpdateRequest{}
	this.SiteId = siteId
	return &this
}

// NewSkuUpdateRequestWithDefaults instantiates a new SkuUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkuUpdateRequestWithDefaults() *SkuUpdateRequest {
	this := SkuUpdateRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *SkuUpdateRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *SkuUpdateRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *SkuUpdateRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SkuUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SkuUpdateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SkuUpdateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *SkuUpdateRequest) GetSchemaVersion() int32 {
	if o == nil || IsNil(o.SchemaVersion) {
		var ret int32
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuUpdateRequest) GetSchemaVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.SchemaVersion) {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *SkuUpdateRequest) HasSchemaVersion() bool {
	if o != nil && !IsNil(o.SchemaVersion) {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given int32 and assigns it to the SchemaVersion field.
func (o *SkuUpdateRequest) SetSchemaVersion(v int32) {
	o.SchemaVersion = &v
}

// GetDeviceType returns the DeviceType field value if set, zero value otherwise.
func (o *SkuUpdateRequest) GetDeviceType() string {
	if o == nil || IsNil(o.DeviceType) {
		var ret string
		return ret
	}
	return *o.DeviceType
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuUpdateRequest) GetDeviceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceType) {
		return nil, false
	}
	return o.DeviceType, true
}

// HasDeviceType returns a boolean if a field has been set.
func (o *SkuUpdateRequest) HasDeviceType() bool {
	if o != nil && !IsNil(o.DeviceType) {
		return true
	}

	return false
}

// SetDeviceType gets a reference to the given string and assigns it to the DeviceType field.
func (o *SkuUpdateRequest) SetDeviceType(v string) {
	o.DeviceType = &v
}

// GetComponents returns the Components field value if set, zero value otherwise.
func (o *SkuUpdateRequest) GetComponents() SkuComponents {
	if o == nil || IsNil(o.Components) {
		var ret SkuComponents
		return ret
	}
	return *o.Components
}

// GetComponentsOk returns a tuple with the Components field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkuUpdateRequest) GetComponentsOk() (*SkuComponents, bool) {
	if o == nil || IsNil(o.Components) {
		return nil, false
	}
	return o.Components, true
}

// HasComponents returns a boolean if a field has been set.
func (o *SkuUpdateRequest) HasComponents() bool {
	if o != nil && !IsNil(o.Components) {
		return true
	}

	return false
}

// SetComponents gets a reference to the given SkuComponents and assigns it to the Components field.
func (o *SkuUpdateRequest) SetComponents(v SkuComponents) {
	o.Components = &v
}

func (o SkuUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkuUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.SchemaVersion) {
		toSerialize["schemaVersion"] = o.SchemaVersion
	}
	if !IsNil(o.DeviceType) {
		toSerialize["deviceType"] = o.DeviceType
	}
	if !IsNil(o.Components) {
		toSerialize["components"] = o.Components
	}
	return toSerialize, nil
}

func (o *SkuUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkuUpdateRequest := _SkuUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkuUpdateRequest)

	if err != nil {
		return err
	}

	*o = SkuUpdateRequest(varSkuUpdateRequest)

	return err
}

type NullableSkuUpdateRequest struct {
	value *SkuUpdateRequest
	isSet bool
}

func (v NullableSkuUpdateRequest) Get() *SkuUpdateRequest {
	return v.value
}

func (v *NullableSkuUpdateRequest) Set(val *SkuUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSkuUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSkuUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkuUpdateRequest(val *SkuUpdateRequest) *NullableSkuUpdateRequest {
	return &NullableSkuUpdateRequest{value: val, isSet: true}
}

func (v NullableSkuUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkuUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
